const permissions =
{
    INSTALL_WIDGET: 3,
    INVITE_MANAGE_TEAMMATE: 4,
    MANAGE_ARTICLES: 5,
    MANAGE_CANNED_RESPONSE: 7,
    MANAGE_CHAT_WIDGET_SETTINGS: 9,
    MANAGE_CONTACTS: 2,
    MANAGE_ATTRIBUTE: 12,
    MANAGE_DATA_TAGS_SEGMENT: 8,
    MANAGE_INBOX: 1,
    MANAGE_TARGETED_EMAIL: 10,
    VIEW_INBOX: 11,
    VIEW_REPORTS: 6
}

export default permissions