name: Build CW Staging
on:
  push:
    branches:
      - staging
    paths:
      - src/widget/**
      - Dockerfile.widget
      - .env.staging
env:
  ECR_DOMAIN: ${{ secrets.STAG_ECR_DOMAIN }}
  ECR_REPO: linebase/lb-fe-cw

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
          
      - name: Generate build ID
        id: prep
        run: |
            branch=${GITHUB_REF##*/}
            sha=${GITHUB_SHA::8}
            ts=$(date +%s)
            echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"   
            
      - name: setup env
        run: |
          cp .env.staging .env

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STAG_AWS_ECR_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STAG_AWS_ECR_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t $ECR_DOMAIN/$ECR_REPO:${{ steps.prep.outputs.BUILD_ID }} -f Dockerfile.widget . --no-cache
          docker push $ECR_DOMAIN/$ECR_REPO:${{ steps.prep.outputs.BUILD_ID }}
